<?php
include("action.php");

$title = "Admin to login";
if (isset($_GET['action'])) {
    $action = htmlspecialchars($_GET['action']);
} else {
    $action = "";
}


// print_r($_SESSION);
// die;
$message = "";
$session_name = "";


if (isset($_GET['msg'])) {
    $msg = $_GET['msg'];
    if ($msg == 'error')
        $message = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>Wrong User Id or Password <button data-bs-dismiss='alert' class='btn-close' type='button'></button></div>";
    if ($msg == 'blank')
        $message = "<div class='alert alert-info alert-dismissible fade show' role='alert'><button data-bs-dismiss='alert' class='btn-close' type='button'></button>User Id & Password Should not blank</div>";
    if ($msg == 'invalid')
        $message = "<div class='alert alert-danger alert-dismissible fade show' role='alert'><button data-bs-dismiss='alert' class='btn-close' type='button'></button>Invalid User login</div>";
    if ($msg == 'logout')
        $message = "<div class='alert alert-success alert-dismissible fade show' role='alert'><button data-bs-dismiss='alert' class='btn-close' type='button'></button>Successfully Logged Out !!</div>";
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="This is admin panel">
    <meta name="author" content="Om Prakash Kashyap">
    <link rel="stylesheet" href="admin/assets/font/bootstrap-icons.css">
    <link rel="stylesheet" href="admin/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="admin/assets/css/style.css">
    <style>
        /* Background styles */
        body {
            background-color: #364571;
        }

        /* Glassmorphism card effect */
        .card {
            backdrop-filter: blur(16px) saturate(180%);
            -webkit-backdrop-filter: blur(16px) saturate(180%);
            background-color: rgba(6, 22, 58, 0.75);
            border-radius: 12px;
            border: 1px solid rgba(209, 213, 219, 0.3);
            margin-top: 30%;
            /* display: none; */
        }

        /* Generated by https://generator.ui.glass/ */
    </style>
</head>

<body>
    <div class="container">

        <div class="col-md-4 offset-md-4">

            <form action="checklogin.php" method="post" class="card card-body shadow">

                <h1 class="text-white">Login</h1>
                <p class="text-light">Login to access your account.</p>
                
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="email_id" name="email_id" placeholder="Enter User Name" value="admin@example.com" autofocus autocomplete="off">
                        <label for="email_id">Email ID    </label>
                    </div>
                    <div class="form-floating">
                        <input type="password" class="form-control" id="admin_pwd" name="admin_pwd" value="admin123"  placeholder="Enter Password">
                        <label for="admin_pwd">Password</label>
                    </div>
                    <div class="d-grid gap-2 mt-3">
                        <button class="btn btn-outline-light" onclick="return checkinputmaster('email_id,admin_pwd')" type="submit" name="login">Login</button>
                    </div>
                    
        
            </form>
        </div>
    </div>

</body>

<!-- script tag -->
<script src="admin/assets/js/jquery-3.6.0.min.js"></script>
<script src="admin/assets/js/bootstrap.bundle.min.js"></script>
<script src="admin/assets/js/commonfun.js"></script>
<script>
    $(document).ready(function() {
        $('.card').fadeIn(2000);
    });
</script>
<!-- script tag -->

</html>